### ISSUE TITLE
Re-evaluate how to check for commit-ish in commit/tag/branch of git modules

### ISSUE THREAD

**Issue by barthalion** [flathub/flatpak-builder-lint#16]
flatpak-builder allows arbitrary commit-ish in all three commit/tag/branch keys. We need to check at least the length of the value to ensure it's actually a commit, and someone doesn't bypass the check by putting tag/branch name in `commit`.

**Comment by hfiguiere** [comment]
or "branch" as "tag"

**Comment by prodrigestivill** [comment]
It should be allowed to use a branch in sources?
Because, it is currently not allowing it.

The actual lint check doesn't allow to have sources that checkout a commit from a branch.
The org.flathub.flatpak-external-data-checker indeed updates to the latest commit from the branch with the following example, but the lint fails.

```yaml
      - type: git
        url: https://github.com/xxx/xxx-translations.git
        branch: master
        commit: 793ae9326330986ab9adfcc380be1561d09365a1
        dest: src/translations
```
